<?php

return [
    'mapping' => [
        'Electrical Systems' => [
            'Accu NS 70',
            'Accu N100',
            'Switch Sign Lamp',
            'Head Lamp',
            'Air Accu',
            'Repair Kabel',
            'Lampu Rotary',
            'Kepala Accu',
            'Charge Accu',
            'Conduit',
            'Kabel Tis',
            'Bohlamp',
            'Isolasi Kabel',
            'Kabel Paralel',
            'Relay dan Saklar',
            'Flasher & Fuse',
            'Alat Charger Accu',
            'Saklar Lampu',
            'Lampu Rem',
        ],
        'Engine Systems' => [
            'Pengelasan Knalpot',
            'Service Dinamo',
            'Pembelian Knalpot',
            'Perbaikan Knalpot',
            'Pengelasan Lips Knalpot',
            'Fanbelt',
            'Stain Chain',
            'Repair Knalpot',
            'Gasket Shaft',
            'Knalpot',
            'Camshaft',
            'Cylinder Liner',
            'Crankshat & Conrod',
            'Hose Intake',
        ],
        'Cooling Systems' => [
            'Radiator Coolant',
            'Kipas Radiator',
            'Service Radiator',
            'Tabung Radiator',
            'Selang Radiator',
            'Klem & Sealer Cooler',
            'Clem Radiator',
            'Perbaikan Tanki',
            'Pengelasan Bumper',
            'Pembelian Cat',
            'Pneumatic',
            'Aksesoris',
            'Sling PTO',
            'Cat Velg',
            'Cross oint PTO',
            'Kabel Sling PTO',
            'Cat dan Tinner',
            'Dempul',
            'Hose Pneumatic',
            'Naple Angin',
            'Hidrolik handrail',
            'Isolasi Cat',
        ],
        'Powertrain' => [
            'Pergantian Kopling',
            'Booster Koopling',
            'Master Kopling',
            'Kopling & Drag Laher',
            'Blade Pompa Corker',
            'Cross Joint',
            'Piston Kopling',
            'Seal Master Kopling',
            'Booster Kopling',
        ],
        'Service' => [
            'Spare Parts',
            'Service',
            'Lubricants',
            'Stooring',
            'Grease',
        ],
        'AC' => [
            'Service AC',
            'Filter AC',
            'V Belt AC',
            'Belt Compressor',
            'Bearing Puly',
            'Isi Freon',
            'Ganti Selang',
        ],
        'Equipment' => [
            'Flexibel Hose',
            'Selang Compresor',
            'Saringan Knalpot',
            'Flexibel SS dan Gasket',
            'Service Alkon',
            'Bearing',
            'Flannge',
            'Selang Pneumatik',
            'Tutup Roda',
            'Seal Kaliper',
            'Padlock Untuk Flowmeter',
            'Duplikat Kunci',
            'Pengelaasan Flexibel Hose',
            'Baut',
            'Kain Majun',
            'Spare Parts Flame',
            'Tools Set',
            'Apar',
        ],
        'Tire' => [
            'Tire',
            'Tire Michelin XZY 3',
            'Tire Michelin XZE 2',
            'Tire Guanda',
            'Tambal Ban',
            'Rotasi Ban',
            'Ban Dalam',
            'Tambah Angin',
            'Semir Ban',
            'Sil Roda',
            'Flap',
            'Tire Bridgestone',
            'Tire Gajah Tunggal',
        ],
        'Brake Systems' => [
            'Slack Adjuster',
            'Brake Lining',
            'King Pin',
            'Kampas Rem',
            'Brake Repair',
            'Cylinder Rem',
            'Seal Kaliper Rem',
            'Minyak Rem',
            'Parking Brake',
            'Karet Rem',
            'Seal Master Rem',
        ],
        'Chasis' => [
            'Perbaikan Karet Dingdong',
            'Spare Parts Spring',
            'Tierod',
            'Pengelasan Calter Oli',
            'Sil Roda',
            'Spring',
            'Ring Spring',
        ],
        'Cabin' => [
            'Karpet Lantai',
            'Jasa Pasang Kaca',
            'Head Lamp',
            'Bracket Wiper',
            'Kaca Film',
            'Handle Pintu',
            'Regulator Window',
            'Kabel Speedometer',
            'Handle Kaca',
        ],
        'Support' => [
            'stickers',
            'Baut',
            'Elektroda Las',
            'Seal',
            'Hose Rail',
            'Kabel Radio',
            'Mata Bor',
            'Slang Klem',
            'Hose Pneumatic',
            'Lem',
            'Mata Gerinda',
            'Stand Chain',
            'Kabel Extension',
            'Bubut Baut',
            'Perpanjangan KEUR',
            'Perpanjangan B3',
            'Perpanjangan Tera',
            'Iklan Kehilangan Buku KEUR',
            'STNK',
            'Izin Lintas',
            'Check Fisik Mutasi Unit',
        ],
        'Wash' => [
            'Wash Fleet',
            'Hose Cucian Armada',
            'Cleaning Tank',
            'Sabun Cuci',
        ],
        'Fuel Systems' => [
            'Injection Pump',
            'Fuel Filter',
            'Pergantian Nozzle',
            'Air Cleaner (Stock)',
            'Tutup Tank BBM',
            'Element Filter (Stock)',
            'Bracket Filter Solar',
            'Selang Bahan Bakar',
            'Nepple dan Coupler',
            'GPS Fuel Sensor',
            'Kalibrasi Injection',
            'Carbon Injector Cleaner',
            'Pom Injection',
        ],
    ]
];